spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/on_demand_driver_solution}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${PORT:8081}
