name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile backend
        run: mvn clean compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test backend
        run: mvn test
